version: 1.2
workflows:
   - subclass: GALAXY
     primaryDescriptorPath: /Dockstore.ga
     authors:
       - orcid:  0000-0002-6130-1021 
       - orcid:  0000-0002-1983-4588
       - orcid:  0000-0002-1983-4588
     testParameterFiles: /Dockstore-job-url.yml     
